### ISSUE TITLE
AttributeError with links with password

### ISSUE THREAD

**Issue by cnxsoft** [banbanchs/pan-baidu-download#11]
Thanks for the great script, but there's an error when downloading from pages asking for a password.

For example:

python bddown_cli.py show http://pan.baidu.com/s/1kTrCcMr --dir=~/Downloads
Please input this sharing password
xpef
Traceback (most recent call last):
  File "bddown_cli.py", line 53, in <module>
    execute_command()
  File "bddown_cli.py", line 49, in execute_command
    commands[command](args[1:])
  File "/media/hdd/edev/sandbox/pan-baidu-download/command/show.py", line 15, in show
    info = pan.get_dlink(url)
  File "/media/hdd/edev/sandbox/pan-baidu-download/bddown_core.py", line 97, in get_dlink
    js = self._get_js(link, secret)
  File "/media/hdd/edev/sandbox/pan-baidu-download/bddown_core.py", line 88, in _get_js
    self.verify_passwd(req.url, secret)
  File "/media/hdd/edev/sandbox/pan-baidu-download/bddown_core.py", line 153, in verify_passwd
    errno = mesg.get('errno')
AttributeError: 'function' object has no attribute 'get'

The password for this link is xpef

**Comment by banbanchs** [comment]
Fixed, but it don't support downloading folder now. So I recommand [this](https://github.com/acgotaku/BaiduExporter) to download folder.
