### ISSUE TITLE
KeyError: 'dlink'

### ISSUE THREAD

**Issue by qiuqiyuan** [banbanchs/pan-baidu-download#16]
I was trying to download a shared folder. 
The exact command I used is:
`pan download --dir=~/Downloads http://pan.baidu.com/s/1sj0qV12`
Then I got the following error report message

```
Traceback (most recent call last):
  File "bddown_cli.py", line 53, in <module>
    execute_command()
  File "bddown_cli.py", line 49, in execute_command
    commands[command](args[1:])
  File "/Users/qqy/workspace/pan-baidu-download/command/download.py", line 56, in download
    info = pan.get_dlink(url, secret)
  File "/Users/qqy/workspace/pan-baidu-download/bddown_core.py", line 125, in get_dlink
    dlink = _json['list'][0]['dlink']
KeyError: 'dlink'
```

**Comment by banbanchs** [comment]
Only support download file for now.
