### ISSUE TITLE
下载时报错

### ISSUE THREAD

**Issue by BevisGoh** [banbanchs/pan-baidu-download#18]
Hi, 我在 Ubuntu 14.04 运行 python bddown_cli.py download ”url“ 时报错，如下：

Traceback (most recent call last):
  File "bddown_cli.py", line 53, in <module>
    execute_command()
  File "bddown_cli.py", line 49, in execute_command
    commands[command](args[1:])
  File "/root/baidu/command/download.py", line 56, in download
    info = pan.get_dlink(url, secret)
  File "/root/baidu/bddown_core.py", line 102, in get_dlink
    js = self._get_js(link, secret)
  File "/root/baidu/bddown_core.py", line 91, in _get_js
    req = self.session.get(link)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))

**Comment by BevisGoh** [comment]
Python 2.7.9

**Comment by BevisGoh** [comment]
在另一台电脑试了，还是报错：

Traceback (most recent call last):
  File "bddown_cli.py", line 53, in <module>
    execute_command()
  File "bddown_cli.py", line 49, in execute_command
    commands[command](args[1:])
  File "/root/baidu/command/download.py", line 56, in download
    info = pan.get_dlink(url, secret)
  File "/root/baidu/bddown_core.py", line 102, in get_dlink
    js = self._get_js(link, secret)
  File "/root/baidu/bddown_core.py", line 91, in _get_js
    req = self.session.get(link)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))

运行环境：
uname -r -> 3.13.0-54-generic
aria2c --version -> aria2 version 1.18.1
python -V -> Python 2.7.6

**Comment by banbanchs** [comment]
`Connection timed out`应该是你网络的问题，我这边一切正常

**Comment by BevisGoh** [comment]
的确是网络问题，现在可以了，谢谢
