### ISSUE TITLE
Can't download files from Baidu anymore

### ISSUE THREAD

**Issue by Kagami** [banbanchs/pan-baidu-download#32]
Hi. For some reason previously valid links now can't be downloaded with your tool. Example:

```
$ pan download http://pan.baidu.com/s/1eQxxdCI --secret 6hsh
Traceback (most recent call last):
  File "/home/kagami/.local/bin/pan", line 53, in <module>
    execute_command()
  File "/home/kagami/.local/bin/pan", line 49, in execute_command
    commands[command](args[1:])
  File "/home/kagami/code/tmp/pan-baidu-download/command/download.py", line 56, in download
    info = pan.get_dlink(url, secret)
  File "/home/kagami/code/tmp/pan-baidu-download/bddown_core.py", line 125, in get_dlink
    js = self._get_js(link, secret)
  File "/home/kagami/code/tmp/pan-baidu-download/bddown_core.py", line 116, in _get_js
    return js[0] or None
IndexError: list index out of range
```

Seems like Baidu has changed API?

**Comment by banbanchs** [comment]
Please login first...

Seem Baidu did not allow download private link anonymously.

Chrome private tab:
![screenshot_20160709_181847](https://cloud.githubusercontent.com/assets/5170232/16707479/cbb64748-4601-11e6-9c68-445ee3f26382.png)

**Comment by Kagami** [comment]
Yes, I noticed the same, but it works after page reload. I think `BAIDUID` cookie is required?
On the first visit there is no such cookie so baidu returns 403 and header `Set-Cookie: BAIDUID=…`. On the next visit I get normal page with secret input field.

**Comment by banbanchs** [comment]
@Kagami interesting, I will fix it later

**Comment by Kagami** [comment]
Now it works, thanks!
