### ISSUE TITLE
Windows 10上UTF-8的支持有问题

### ISSUE THREAD

**Issue by mengmo** [banbanchs/pan-baidu-download#42]
因为`命令提示符`默认代码页为`GBK`，中文会显示乱码
所以，`chcp 65001`将活动代码页转换为`UTF-8`。
下载会出错
```
python bddown_cli.py download http://pan.baidu.com/s/1c2iM8AO
Please input this sharing password
bpb4
Traceback (most recent call last):
  File "bddown_cli.py", line 53, in <module>
    execute_command()
  File "bddown_cli.py", line 49, in execute_command
    commands[command](args[1:])
  File "D:\PortableApps\pan-baidu-download\command\download.py", line 110, in download
    download_command(fi.filename, savedir, fi.dlink, cookies=cookies, limit=limit, output_dir=output_dir)
  File "D:\PortableApps\pan-baidu-download\command\download.py", line 18, in download_command
    print("\033[32m" + filename + "\033[0m")
LookupError: unknown encoding: cp65001
```

**Comment by HephaestusA0** [comment]
可以用CHCP 65001 CMD命令来解决UTF-8 乱码问题
