### ISSUE TITLE
可否给一个更加傻瓜的使用说明呢， baiduurl是我自己网盘的url还是文件分享的url呢？

### ISSUE THREAD

**Issue by LouisLuFin** [banbanchs/pan-baidu-download#58]
在终端运行时出现
python bddown_cli.py download [https://pan.baidu.com/s/1CmYofIP9kfaG7ZQSxJZf5w]
Traceback (most recent call last):
  File "bddown_cli.py", line 8, in <module>
    from util import bd_help, usage
  File "/Users/louis/pan-baidu-download/util.py", line 9, in <module>
    from requests.utils import dict_from_cookiejar
ImportError: No module named requests.utils

**Comment by dsx724** [comment]
sudo apt-get install python-requests aria2
